{% set name = "xpdConf" %}
{% set version = "0.4.1" %}
{% set sha256 = "2a1ca83ac3351180eea04df0c5c6e0e3b8fb7d0bf954215edf07f0621f56143a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/xpdAcq/{{ name }}/releases/download/{{ version }}/xpdConf-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip
    - setuptools
  run:
    - python
    - databroker
    - pyyaml

test:
  imports:
    - xpdconf

about:
  home: http://github.com/xpdAcq/xpdConf
  license: BSD-3-Clause 
  license_family: BSD
  license_file: LICENSE
  summary: 'Configuration for XPD beamlines'

extra:
  recipe-maintainers:
    - CJ-Wright
    - chiahaoliu
    - sbillinge
