{% set name = "xpdConf" %}
{% set version = "0.4.5" %}
{% set sha256 = "63d50b8cce841eb47a45aa92376db48843a3e1db4e014eead7ad22399ce33e9f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/xpdAcq/{{ name }}/releases/download/{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install --no-deps .

requirements:
  build:
    - python >=3.8
    - pip
    - setuptools
  run:
    - python >=3.8, <3.10
    - databroker <2.0.0a
    - pyyaml

test:
  imports:
    - xpdconf
    - xpdconf.conf

about:
  home: http://github.com/xpdAcq/xpdConf
  license: BSD-3-Clause 
  license_family: BSD
  license_file: LICENSE
  summary: 'Configuration for XPD beamlines'
  doc_url: https://github.com/xpdAcq/xpdConf
  dev_url: https://github.com/xpdAcq/xpdConf

extra:
  recipe-maintainers:
    - sbillinge
    - st3107
